// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRTWiCttmYGEsURFejgBmTaenN17tVngA',
    appId: '1:134943825538:web:267254cfe70e5932891e9b',
    messagingSenderId: '134943825538',
    projectId: 'herodex-1928e',
    authDomain: 'herodex-1928e.firebaseapp.com',
    storageBucket: 'herodex-1928e.firebasestorage.app',
    measurementId: 'G-Q235J40QTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUDUdsUAA9TIxp3Va3qMowUcoBz_zqpg8',
    appId: '1:134943825538:android:ca9f2d66e46199c5891e9b',
    messagingSenderId: '134943825538',
    projectId: 'herodex-1928e',
    storageBucket: 'herodex-1928e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2kEouiOiKYjMjUkQv9HfertAtNEWfqDc',
    appId: '1:134943825538:ios:cd2797ad32f91a5c891e9b',
    messagingSenderId: '134943825538',
    projectId: 'herodex-1928e',
    storageBucket: 'herodex-1928e.firebasestorage.app',
    iosBundleId: 'com.example.herodex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2kEouiOiKYjMjUkQv9HfertAtNEWfqDc',
    appId: '1:134943825538:ios:cd2797ad32f91a5c891e9b',
    messagingSenderId: '134943825538',
    projectId: 'herodex-1928e',
    storageBucket: 'herodex-1928e.firebasestorage.app',
    iosBundleId: 'com.example.herodex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRTWiCttmYGEsURFejgBmTaenN17tVngA',
    appId: '1:134943825538:web:58e619276e5ba481891e9b',
    messagingSenderId: '134943825538',
    projectId: 'herodex-1928e',
    authDomain: 'herodex-1928e.firebaseapp.com',
    storageBucket: 'herodex-1928e.firebasestorage.app',
    measurementId: 'G-M06CFDF7K6',
  );
}
